language: python

services:
- couchdb

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
  - pypy3

notifications:
  email:
    recipients:
      - rinat.sabitov@gmail.com
    on_success: change
    on_failure: change

install:
  - pip install "pip<8.0.0" 
  - pip install "coverage==3.7.1"
  - pip install unittest2
  - pip install mock requests nose responses coveralls

script:
  - nosetests -vv --with-coverage --cover-erase --cover-package=pycouchdb --with-doctest

after_success:
    - coveralls
